# Generated by Django 4.2.2 on 2023-06-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_campo', models.CharField(choices=[('string', 'Texto'), ('number', 'Numérico'), ('bool', 'Booleano')], max_length=6)),
                ('exibir_no_formulario', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Campos Adicionais',
                'db_table': 'campo_adicional',
            },
        ),
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaopropostas.campoadicional')),
            ],
            options={
                'verbose_name_plural': 'Custom Fields',
                'db_table': 'custom_fields',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('data_proposta', models.DateTimeField(auto_now_add=True)),
                ('campos_adicionais', models.ManyToManyField(through='gestaopropostas.CustomFields', to='gestaopropostas.campoadicional')),
            ],
        ),
        migrations.AddField(
            model_name='customfields',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaopropostas.proposta'),
        ),
    ]
